wp-document-revisions/wp-document-revisions

- includes/admin.php
The general query filters on list view no longer apply to the grid view populated via ajax. This commit is somewhat of a bandaid that applies the same filters used for list view to the query made over ajax. It should be okay for long term use, but may need a closer look at some point.
> [PR] Filter documents from the grid view in Media, queried via Ajax

- includes/admin.php
Solved:  https://wordpress.org/support/topic/previous-versions-of-document-give-404-not-found
> Added code to preserve file exts on revision links

- wp-document-revisions.php
When a file is uploaded directly to the media library in grid view, rather than as an attachment, `$_POST['post_id']` is not available and will generate an error in the AJAX response. We can assume that if post ID is not available, this is not a document.
> Verify a post ID has been passed before verifying post type

- .travis.yml
- bin/install-wp-tests.sh
- includes/HTTP/WebDAV/Server.php
- includes/HTTP/WebDAV/Tools/_parse_lockinfo.php
- includes/HTTP/WebDAV/Tools/_parse_propfind.php
- includes/HTTP/WebDAV/Tools/_parse_proppatch.php
- tests/bootstrap.php
- tests/test_document_revisions.php
- tests/test_document_rewrites.php
- wp-document-revisions.php
Howdy. I've been wanting to dive a little deeper into what maintenance of WP Document Revisions would look like and I figure the first step is to make sure the existing test structure is working. I'll follow up in #68 with some other thoughts too. :)
A variety of changes here, but the tests *should* now pass again:
* Updated the test scaffolding to the most recent `install-wp-tests.sh` and `.travis.yml` provided by the WP-CLI project. This addresses issues with the tests working at all on newer WP versions.
* Avoid a PHP notice by checking for `HTTP_USER_AGENT` before using it in the WebDAV code. The tests don't set this.
* Ensure the full upload path exists before copying test files. Previously, the first test would pass and the others would fail because the upload directory was deleted. …
> [PR] Make tests pass

- includes/admin.php
In WordPress 4.3, admin page headings were changed to use H1 as the main heading. Other heading levels can be updated to match.
See https://make.wordpress.org/core/2015/07/31/headings-in-admin-screens-change-in-wordpress-4-3/
Fixes #88.
> [PR] Use H2 for "Feed Privacy" heading

- .travis.yml
PHP 5.3 is not supported on Trusty, which is used by default in Travis.
See https://docs.travis-ci.com/user/reference/trusty#PHP-images
This should resolve the current CI errors.
(Sorry for bailing on you earlier in the year, @benbalter. Things got nuts 🙈 )
> Use Ubuntu Precise for PHP 5.3 build on Travis

- composer.json
- includes/class-wp-document-revisions-admin.php
- includes/class-wp-document-revisions-front-end.php
- includes/class-wp-document-revisions.php
- phpcs.ruleset.xml
- tests/class-test-wp-document-revisions-front-end.php
- tests/class-test-wp-document-revisions-rewrites.php
- tests/class-test-wp-document-revisions.php
- wp-document-revisions.php
[WPCS 0.14.0 was released a few days ago](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/0.14.0) and several new rules are applied.
> [PR] Update WPCS and adjust code to meet new standards

- includes/class-wp-document-revisions-admin.php
- includes/class-wp-document-revisions.php
- tests/class-test-wp-document-revisions.php
**Original reported issue:** When documents appear in search results, and a site's theme (Twenty Seventeen) is using a custom logo, the custom logo does not display. 
**Resolution:** WP Document Revisions was applying its `image_downsize` filtering to all images on the search page view because the first result was a document and `verify_post_type()` assumed a document page load.
The `verify_post_type()` method assumes `false` if no other data is passed to it and attempts to determine a valid post ID based on the global data available to it. In some cases, this determination
can be wrong due to how things are passed around in WordPress.
In several cases, we already have a `WP_Post` object or post ID and can call `verify_post_type( $arg )` with that data directly. In other cases, we really …
> Fix possible data pollution in archive views

- includes/class-wp-document-revisions.php
In some cases, `apply_filters( 'the_title' ... )` is called by other plugins without passing the post ID. We should fallback to `null` and skip title processing when this is the case.
Introduced in 54d017c33b81591525.
> Account for `the_title` filter used with only one arg

- includes/class-wp-document-revisions.php
When using a plugin such as [S3 Uploads](https://github.com/humanmade/S3-Uploads), the AWS S3 SDK stream wrapper for PHP [does not include support](https://forums.aws.amazon.com/message.jspa?messageID=505342) for `mime_content_type`. When `mime_content_type()` fires on the S3 SDK stream resource, an error like `PHP Warning:  mime_content_type(): Failed identify data 0:invalid mode 00` appears. S3 Uploads instead provides a [replacement method](https://github.com/humanmade/S3-Uploads/blob/bcb0a70980bcb102c8705627601ed977bdf2c3c9/inc/class-s3-uploads-local-stream-wrapper.php#L78) for mime type detection. 
Additionally, in some server configurations it's possible that the `Content-Type` header set here does not make its way to the response and accounts instead for extra overhead.
To allow …
> Provide a way to filter or skip mime type detection

- includes/class-wp-document-revisions.php
If `0` is passed to `verify_post_type()` and a global post object is not available, then immediately return `false`.
This caused a warning when viewing the media library. Introduced in 54d017c33b815915253674b63d169c508a43277a 🎉 .
> Don't verify posts that don't exist

- includes/class-wp-document-revisions.php
Function i18n has been moved to sub-folder /includes, so needs to be removed from the path name. Version 2.2 was called from main folder.
Also WP translate documentation states that this should be called at plugins-loaded, so linked to that action.
> Addresses issue #102 - Translations do not work.

- includes/class-wp-document-revisions.php
When using WP Document Revisions in a multisite installation, there were issues with the uploads folder setting when using the plugin both on the main site (usually site with ID = 1) and on other sub-sites. This pull request fixes that by removing the site-specific part for the main site.
> Fixes #111: Multisite issue with main site

- includes/class-wp-document-revisions.php
This is issue #116 (and possibly #82)
When using a permalink, the process serve_file uses get_attached_file which uses a cached version of the upload directory without direct reference to the specific post.
This gives the standard directory. If the user has defined a different directory then this is not used  - and the 404 results.
> For using Permalinks with changed directory

- includes/class-wp-document-revisions-admin.php
- includes/class-wp-document-revisions.php
There are two groups of fixes; I can split out if needed.
1. WP has changed the name of the filter to use (in WP 3.1.)
2. Sanitizing of html text has sanitized <code> when it should not have done.
Item 1 will require an update to the Cookbook code - but this needs updating in any case.
I will provide an update for this.
> Small fixes in Admin function

- css/style-front.css
- includes/class-wp-document-revisions-admin.php
- includes/class-wp-document-revisions-front-end.php
- includes/class-wp-document-revisions.php
This change allows the document shortcode to have an additional edit option.
By default this is only allowed for administrators, but a filter is provided to modify it.
The user does then needs the edit_document capability for each individual document for this to be displayed.
This mirrors the capability to have an edit page option on a page but to see the page ordinarily and not to navigate via the Pages admin option.
It also permits the user to display the document directly as before.
> Create Edit link on document shortcode

- docs/changelog.md
- docs/header.md
- readme.txt
Featured Image support bumped the version to 3.2 but some documentation references were not updated.
The WP tested versions has been updated to 4.9.8
Documentation change only
> Bump version to V3.2 and Tested WP 4.9.8

- includes/class-wp-document-revisions.php
Fixes https://github.com/benbalter/wp-document-revisions/issues/135.
> Fix for $wp_query->query_vars being null

- includes/class-wp-document-revisions-admin.php
- includes/class-wp-document-revisions.php
Currently when the plug-in is inactivated and then reactivated, the capabilities revert to the supplied set so, if changed, would need manually resetting to their desired settings.  
By only adding them if they are not present for each role, they will retain their existing values.
> Add the default capabilities only when they are absent.

- composer.json
- composer.lock
- includes/class-wp-document-revisions-admin.php
- includes/class-wp-document-revisions-front-end.php
- includes/class-wp-document-revisions-recently-revised-widget.php
- includes/class-wp-document-revisions.php
- includes/revision-feed.php
- phpcs.ruleset.xml
- tests/bootstrap.php
- tests/class-test-wp-document-revisions-front-end.php
- tests/class-test-wp-document-revisions-rewrites.php
- tests/class-test-wp-document-revisions.php
- wp-document-revisions.php
phpcs:ignore replaces @codingStandards so comments updated.
Some sniffs have been renamed so code updated in line.
Excludes that can be auto fixed have been (except for line endings as these can vary between PC, Linux and Mac).
> PHPCS review

- docs/changelog.md
- includes/class-wp-document-revisions.php
- readme.txt
- wp-document-revisions.php
This addresses the issues identified in #254.
Realised the problem that I had yesterday and are now getting the file length correctly.
Can support deflate compression as it's simply a case of calling a different PHP function and labelling the encoding appropriately. x-gzip is simply a synonym for gzip.
Whilst I believe that I could have written the length header for HTTP/2, but since it's optional... (and I don't have an http/2 site available to me to test.)
I have restructured the processing within serve_file quite a bit, but it is really to ensure that I don't output any headers until the last possible moment. However for a 304, that's quite early.
I do hope that this resolved all the issues seen in delivering the files to users.
I have labelled this as a 3.3.1 release. 
Regards,
Neil
> Address HTTP/2 File Length issues

- includes/class-wp-document-revisions-validate-structure.php
When doing the write-up, I noticed that the code did not match the intended description - in that I had not checked that the attachment described in post_content actually belonged to the document. So I added the test.
I did not test that the $doc_id (document id) was type compatible with the attachment post_parent.
So the test I added failed.
Apologies for my error.
Neil
> $doc_id parameter is string needs to be cast to int.

- docs/changelog.md
- docs/data-structure.md
- docs/filters.md
- includes/class-wp-document-revisions-admin.php
- includes/class-wp-document-revisions-front-end.php
- includes/class-wp-document-revisions-validate-structure.php
- includes/class-wp-document-revisions.php
- readme.txt
- wp-document-revisions.php
@benbalter 
Sorry it has taken a time to revert with the fix to the problem I had raised with you to release V3.6.
I had hoped to address the issues for WPML.
Whilst I think think that I have them sorted (mentally at least), I think the most appropriate way to deal with it is to a plugin to go in the Cookbook that will be the functions to interface WPML, and to add filters and/or actions (if necessary) to the plugin.
I have changed the way the PDF image denotes that it has hidden itself to be better aligned with WPML processing. It will be marginally more efficient in processing than having a separate piece of metadata.
I have also fixed the issue raised today on Github which is a text typo.
Separately I wrote a document giving information on the data structures used. This was if I needed …
> Address issue to release Version 3.6

- includes/class-wp-document-revisions.php
Property subdir is required, so don't remove it during the filter, just set it to an empty string. 
https://developer.wordpress.org/reference/functions/wp_upload_dir/
> Update class-wp-document-revisions.php - property subdir is required.

- includes/class-wp-document-revisions-admin.php
This PR fixes an error that I've seen where the following error is returned.
```
TypeError: Cannot read properties of undefined (reading 'bindPostDocumentUploadCB')
at HTMLDocument.<anonymous> (VM5802 media-upload.php:3:33)
```
To reproduce the error. 
- Open console in browser
- Create a new document
- Click Upload new version.
- You will see the error is logged.
> Fix: TypeError: window.WPDocumentRevisions is undefined

- includes/class-wp-document-revisions-recently-revised-widget.php
Changes have already been made to ensure translations are only done on/after the init hook.
WP 6.8 includes a doing_it_wrong call for translations - showing that the widget __construct call was being done during plugin_loaded, i.e. earlier that included translations.
This fix ensures that translation calls are not done prior to the init hook.
> Translations should only be called on/after init

- includes/class-wp-document-revisions.php
Previous to this change, a document slug could be set with non-allowed characters, e.g. whitespace.
> Update sanitize function for slug in `update_post_slug_field`
